# Generated by Django 6.0.3 on 2026-04-10 18:29

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_course_id_alter_course_image_alter_level_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='image',
            field=cloudinary.models.CloudinaryField(default='language_center_testing/courses/lxkpvpnsh95v520gb0on.webp', max_length=255),
        ),
    ]
