# Generated by Django 6.0.3 on 2026-04-10 18:40

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_alter_course_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='image',
            field=cloudinary.models.CloudinaryField(default='language_center_testing/courses/lxkpvpnsh95v520gb0on', max_length=255),
        ),
    ]
