# Generated by Django 6.0.3 on 2026-03-24 06:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(choices=[('MOMO', 'MoMo'), ('VNPAY', 'VNPay')], default='VNPAY', max_length=20)),
                ('transaction_id', models.CharField(max_length=255, unique=True)),
                ('paid_at', models.DateTimeField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enrollment_status', models.CharField(choices=[('SUCCESS', 'Đăng ký thành công'), ('PENDING_PAYMENT', 'Đang chờ thanh toán'), ('PARTIAL_PAYMENT', 'Thanh toán một phần')], default='PENDING_PAYMENT', max_length=20)),
                ('payment_deadline', models.DateTimeField(blank=True, null=True)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='classes.classroom')),
            ],
        ),
    ]
