# Generated by Django 6.0.3 on 2026-04-07 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0003_alter_enrollment_id_alter_payment_id'),
        ('enrollments', '0003_rename_user_enrollment_student_and_more'),
    ]

    operations = [
    ]
