# Generated by Django 6.0.3 on 2026-04-11 16:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0008_schedule_idx_schedule_class_and_more'),
        ('courses', '0005_alter_course_image'),
        ('enrollments', '0005_alter_enrollment_id_alter_payment_id'),
        ('grades', '0003_alter_academicresult_id_alter_attendance_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='enrollment',
            unique_together=set(),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['classroom'], name='idx_enrollment_class'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['enrollment'], name='idx_payment_enrollment'),
        ),
        migrations.AddConstraint(
            model_name='enrollment',
            constraint=models.UniqueConstraint(fields=('student', 'classroom'), name='uk_enrollment_user_class'),
        ),
    ]
