# Generated by Django 6.0.3 on 2026-04-20 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0004_merge_20260407_2007'),
        ('enrollments', '0007_payment_payment_status_alter_payment_paid_at_and_more'),
    ]

    operations = [
    ]
