# Generated by Django 4.2.30 on 2026-04-22 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0008_merge_20260420_2156'),
        ('enrollments', '0008_merge_20260421_2231'),
    ]

    operations = [
    ]
