# Generated by Django 6.0.3 on 2026-03-31 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0003_rename_user_teachingassignment_teacher_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='grade_deadline',
            field=models.DateTimeField(null=True),
        ),
    ]
