# Generated by Django 6.0.3 on 2026-04-07 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0005_alter_classroom_id_alter_room_id_alter_schedule_id_and_more'),
        ('classes', '0005_alter_session_user'),
    ]

    operations = [
    ]
