# Generated by Django 4.2.29 on 2026-04-07 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0005_alter_classroom_id_alter_room_id_alter_schedule_id_and_more'),
        ('classes', '0005_alter_session_user'),
    ]

    operations = [
    ]
