# Generated by Django 6.0.3 on 2026-04-11 16:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0007_alter_classroom_id_alter_room_id_alter_schedule_id_and_more'),
        ('enrollments', '0005_alter_enrollment_id_alter_payment_id'),
        ('grades', '0003_alter_academicresult_id_alter_attendance_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='schedule',
            index=models.Index(fields=['classroom'], name='idx_schedule_class'),
        ),
        migrations.AddIndex(
            model_name='schedule',
            index=models.Index(fields=['room'], name='idx_schedule_room'),
        ),
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['schedule'], name='idx_session_schedule'),
        ),
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['room'], name='idx_session_room'),
        ),
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['user'], name='idx_session_teacher'),
        ),
        migrations.AddConstraint(
            model_name='teachingassignment',
            constraint=models.UniqueConstraint(fields=('teacher', 'classroom'), name='uk_teacher_class'),
        ),
    ]
