# Generated by Django 6.0.3 on 2026-04-16 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0008_schedule_idx_schedule_class_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
