# Generated by Django 6.0.3 on 2026-04-16 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0009_classroom_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classroom',
            name='is_active',
        ),
    ]
