# Generated by Django 6.0.3 on 2026-04-16 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0010_remove_classroom_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classroom',
            name='active',
        ),
    ]
