# Generated by Django 6.0.3 on 2026-04-16 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0011_remove_classroom_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
