# Generated by Django 6.0.3 on 2026-04-20 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0006_merge_20260407_2007'),
        ('classes', '0012_classroom_active'),
    ]

    operations = [
    ]
