# Generated by Django 4.2.30 on 2026-04-21 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0006_merge_20260407_2007'),
        ('classes', '0012_classroom_active'),
    ]

    operations = [
    ]
