# Generated by Django 6.0.3 on 2026-04-11 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0008_schedule_idx_schedule_class_and_more'),
        ('courses', '0005_alter_course_image'),
        ('enrollments', '0006_alter_enrollment_unique_together_and_more'),
        ('grades', '0003_alter_academicresult_id_alter_attendance_id_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['session'], name='idx_attendance_session'),
        ),
        migrations.AddIndex(
            model_name='score',
            index=models.Index(fields=['enrollment'], name='idx_score_enrollment'),
        ),
        migrations.AddIndex(
            model_name='score',
            index=models.Index(fields=['score_type'], name='idx_score_type'),
        ),
        migrations.AddConstraint(
            model_name='attendance',
            constraint=models.UniqueConstraint(fields=('enrollment', 'session'), name='uk_attendance_enrollment_session'),
        ),
    ]
