# Generated by Django 6.0.3 on 2026-03-23 12:47

import cloudinary.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('avatar', cloudinary.models.CloudinaryField(default='https://res.cloudinary.com/desvczltb/image/upload/v1766290194/student_4297861_lyjelp.png', max_length=255)),
                ('phone_num', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='auth_provider',
            field=models.CharField(choices=[('LOCAL', 'Local'), ('GOOGLE', 'Google'), ('FACEBOOK', 'Facebook')], default='LOCAL', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='provider_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
