# Generated by Django 6.0.3 on 2026-03-24 06:28

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
        ('enrollments', '0001_initial'),
        ('users', '0002_profile_user_auth_provider_user_provider_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='classrooms',
            field=models.ManyToManyField(related_name='teached_classes', through='classes.TeachingAssignment', to='classes.classroom'),
        ),
        migrations.AddField(
            model_name='user',
            name='enrollments',
            field=models.ManyToManyField(related_name='enrolled_classes', through='enrollments.Enrollment', to='classes.classroom'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=cloudinary.models.CloudinaryField(default='language_center_testing/defaults/student_4297861_lyjelp', max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='auth_provider',
            field=models.CharField(choices=[('LOCAL', 'Tài khoản hệ thống'), ('GOOGLE', 'Tài khoản Google'), ('FACEBOOK', 'Tài khoản Facebook')], default='LOCAL', max_length=20),
        ),
    ]
