# Generated by Django 6.0.3 on 2026-03-27 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_initial'),
        ('enrollments', '0002_initial'),
        ('users', '0003_user_classrooms_user_enrollments_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='classrooms',
            field=models.ManyToManyField(related_name='teachers', through='classes.TeachingAssignment', to='classes.classroom'),
        ),
        migrations.AlterField(
            model_name='user',
            name='enrollments',
            field=models.ManyToManyField(related_name='students', through='enrollments.Enrollment', to='classes.classroom'),
        ),
    ]
