# Generated by Django 4.2.30 on 2026-04-22 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_user_role_delete_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone_num',
            field=models.CharField(blank=True, default=None, max_length=10, null=True, unique=True),
        ),
    ]
