# Generated by Django 6.0.3 on 2026-04-07 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_profile_phone_num'),
        ('users', '0008_alter_user_id'),
    ]

    operations = [
    ]
